config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :pictures
  resources :comments
  
   # custom routes
  get "/search", to: "pictures#search"
  # get 'comments/new'
  # get 'comments/create'
  # get 'comments/destroy'
  # get 'pictures/new'
  # get 'pictures/create'
  # get 'pictures/show'
  # get 'pictures/edit'
  # get 'pictures/update'
  # get 'pictures/destroy'
  # get 'categories/index'
  # get 'categories/new'
  # get 'categories/create'
  # get 'categories/show'
  # get 'categories/edit'
  # get 'categories/update'
  # get 'categories/destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

  #VALIDATIONS
  validates :name, presence: {message: "Name can't be blank"}
  #validates :cover, presence: {message: "Cover can't be blank"}

  #ASSOCIATIONS
  has_many :pictures, dependent: :destroy
  has_one_attached :cover

end

app/models/comment.rb
class Comment < ApplicationRecord

  #VALIDATIONS
  validates :content, length: { in: 1..150 }

  #ASSOCIATIONS
  belongs_to :picture, counter_cache: true

end

app/models/picture.rb
class Picture < ApplicationRecord
  #VALIDATIONS
  validates :title, presence: {message: "Title can't be blank"}
  #validates :photo, presence: {message: "Image can't be blank"}

  #ASSOCIATIONS
  has_many :comments, dependent: :destroy
  belongs_to :category, counter_cache: true, optional: true
  has_one_attached :photo

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET	/categories
  def index
    @categories=Category.all
  end

  # GET	/categories/:id
  def show
    @category = Category.find(params[:id])
    @pictures = @category.pictures
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      # /departments/4
      # redirect_to "/departments/#{@department.id}"
      # redirect_to department_path(@department)
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    
    if @category.update(category_params)
      redirect_to categories_path
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to pictures_path, status: :see_other
  end

  private
  def category_params
    params.require(:category).permit(:name, :description, :cover)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET	/comments/new
  def new
    @comment = Comment.new
  end

  # POST	/comments
  def create
    @comment = Comment.new(comment_params)
  end

  # DELETE	/comments/:id
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to picture_path, status: :see_other
  end

  private
  def category_params
    params.require(:comment).permit(:description)
  end
end

app/controllers/concerns/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET	/pictures/new
  def new
    @picture = Picture.new
  end

  # GET	/pictures/:id
  def show
    @picture = Picture.find(params[:id])
    @comments = @picture.comments
  end

  def create
    @picture = Picture.new(picture_params)

    if @picture.save
      # /departments/4
      # redirect_to "/departments/#{@department.id}"
      # redirect_to department_path(@department)
      redirect_to @picture
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update(picture_params)
      redirect_to pictures_path
    else
      render "edit", status: :unprocessable_entity
    end
  end

  # DELETE	/pictures/:id
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    redirect_to categories_path, status: :see_other
  end

  # GET /search?query=
  def search
    @query = params[:query]
    if !@query.nil?
    @pictures = Picture.where("LOWER(title) LIKE ?", "%#{@query.downcase}%")
    end
    # render "search"
  end

  private
  
  def picture_params
    params.require(:picture).permit(:name, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1 class="edit_h1">Edit Category</h1>

<%= form_with model: @category do |form| %>
    <% @category.errors.full_messages_for(:name).each do |message|%>
        <span><%= message %></span><br/><br/>
    <% end %>
    <%# <% @category.errors.full_messages_for(:description).each do |message|%>
        <%#<span><%= message %><%#</span> %>
    <%#<% end %>
    <div>
        <label class="edit_name">NAME</label><br>
        <%= form.text_field :name, class: "edit_name_text" %>
    </div>

    <div>
        <label class="edit_name">DESCRIPTION</label><br>
        <%= form.text_area :description, class: "edit_description" %>
    </div>


    <label class="edit_name">COVER</label><br>
<input type="file" accept="image/png, image/jpeg, image/jpg" class="edit_input_file"><br>

    <%= form.submit "Edit Category", class: "edit_input_submit" %>
    <div>
    <%= link_to "Back", categories_path, class: "edit_input_back"  %>
    </div>
<% end %>

app/views/categories/index.html.erb
<section class="container-ss">
<h1 class="margin-bottom-22">Categories</h1>
<div>
    <%= link_to "New category", new_category_path, class:"button--nw button--sm" %>
</div>



<% @categories.each do |category| %>
<div>
  <%= link_to image_tag(category.cover, class:"border-radius-tlr-6 card-shadow-lr margin-top-16"), category_path(category)%>
  <div>
   <div>
    <h3 class="padding-lr-16 padding-t-8"><%= category.name %></h3>
    <p class="padding-lr-16"><%= category.pictures_count %> photos</p>
    <p class="padding-lr-16"><%= category.description %></p>
   </div>
   <div class="padding-lr-16 float-right">
    <%= link_to edit_category_path(category) do %>
    <i class="ri-pencil-line"></i>
    <% end %>
    <%= link_to category_path(category), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
    } do%>
    <i class="ri-delete-bin-line"></i>
    <% end %>
   <div><br>
  </div>
</div>
<% end %>
</section>

app/views/categories/new.html.erb
<h1 class="edit_h1">New Category</h1>
<div>
  <% @category.errors.full_messages.each do |message| %>
  <div><%= message %></div>
  <% end %>
</div>

<%= form_with model: @category do |form| %>
<div>
  <label class="edit_name">NAME</label><br>
  <%= form.text_field :name, class: "edit_name_text" %>
</div>  

<div>
  <label class="edit_name">DESCRIPTION</label><br>
  <%= form.text_area :description, class: "edit_description" %>
</div>

<label class="edit_name" >COVER</label><br>
<input type="file" accept="image/png, image/jpeg, image/jpg" class="edit_input_file"><br><br>

<%= form.submit "Create Category", class: "edit_input_submit" %>

<div>
  <%= link_to "Back", categories_path, class: "edit_input_back"%>
</div>
<% end %>

app/views/categories/show.html.erb
<section class="container-ss">
<h1><%=@category.name%></h1>
<p class="margin-bottom-22"><%=@category.description%></p>
<div>
    <%= link_to "New photo", new_picture_path, class:"button--nw button--sm" %>
</div>



<% @pictures.each do |picture| %>
<div>
  <%= link_to image_tag(picture.photo, class:" margin-top-16"), picture_path(picture)%>
  <div>
   <div>
    <h3 class="padding-lr-16 padding-t-8"><%= picture.title %></h3>
   </div>
   <div class="flexbox-space-between">
     <p class="padding-lr-16"><%= picture.comments_count %> comments</p>
     <div class="padding-lr-16">
        <%= link_to edit_picture_path(picture) do %>
        <i class="ri-pencil-line"></i>
        <% end %>
        <%= link_to picture_path(picture), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
        } do%>
        <i class="ri-delete-bin-line"></i>
        <% end %>
       <div><br>
     </div>
  </div>
</div>
<% end %>

<div>
  <%= link_to "Back", categories_path %>
</div>
</section>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/new.html.erb
<%= form_with model: @category do |form| %>
<div>
  <%= form.text_area :description %>
</div>

<%= form.submit value="COMMENT" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SomesplashC8Team4Week10</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <%# imagen splash %>
        <%= link_to "Search", search_path %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/edit.html.erb
<h1 class="edit_h1">Edit Picture</h1>

<%= form_with model: @picture do |form| %>
    <% @picture.errors.full_messages_for(:name).each do |messages|%>
        <span><%= message %></span>
    <% end %>
    <div>
        <label class="edit_name">TITLE</label><br>
        <%= form.text_field :title, class: "edit_name_text" %>
    </div>

    <div>
        <label class="edit_name">DESCRIPTION</label>
        <%= form.text_area :description, class: "edit_description" %>
    </div>

    <% @picture.errors.full_messages_for(:description).each do |messages|%>
        <span><%= message %></span>
    <% end %>

    <label class="edit_name">CATEGORY</label><br/>
    <select name="CATEGORY" class="edit_select">
    <% Category.all.each do |category| %>
        <option value=<%category.name%>><%=category.name%></option>
    <%end%>
    </select>

    <label class="edit_name">IMAGE</label><br/>
    <input class="edit_input_file" type="file" accept="image/png, image/jpeg, image/jpg"><br/>


    <%= form.submit "EDIT PHOTO", class: "edit_input_submit" %>
    <div>
        <%= link_to "Back", :back, class: "edit_input_back" %>
    </div>
<% end %>

app/views/pictures/new.html.erb
<h1 class="edit_h1">New Photo</h1>
<div>
  <% @picture.errors.full_messages.each do |message| %>
  <div><%= message %></div>
  <% end %>
</div>

<%= form_with model: @picture do |form| %>
<div>
  <label class="edit_name">TITLE</label><br>
  <%= form.text_field :title, class: "edit_name_text" %>
</div>

<div>
  <label class="edit_name">DESCRIPTION</label>
  <%= form.text_area :description, class: "edit_description" %>
</div> <br/>

<label class="edit_name" >CATEGORY</label><br/>
<select name="CATEGORY" class="edit_select">
  <% Category.all.each do |category| %>
    <option value=<%category.name%>><%=category.name%></option>
  <%end%>
</select>

<label class="edit_name">IMAGE</label><br/>
<input class="edit_input_file" type="file" accept="image/png, image/jpeg, image/jpg"><br/><br/>

<%= form.submit "CREATE PHOTO", class: "edit_input_submit" %>

<div>
  <%= link_to "Back", :back, class: "edit_input_back" %>
</div>
<% end %>

app/views/pictures/search.html.erb
<h1 class="edit_h1">Search</h1>  
<%= form_with url: "/search", method: :get do |form| %>
    <%= form.text_field :query, placeholder: "search", class: "edit_name_text" %>
    <%= form.submit "SEARCH PHOTOS", class: "edit_input_submit"%>
<% end %>

<% if @query %>
<p><%= @pictures.size %> pictures found</p><br/>
<% @pictures.each do |picture| %>
  <div><%= image_tag picture.photo %></div>

<%= picture.title %><br>
<%= picture.comments_count %> comments <br>
<%= link_to "show", picture_path(picture)%>
<%= link_to "edit", edit_picture_path(picture) %>
<%= link_to "destroy", picture_path(picture), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
    }%><br>
<% end %>

<% end %>
<div>
  <%= link_to "Back", categories_path , class: "edit_input_back" %>
</div>

app/views/pictures/show.html.erb
<h1><%= @picture.title %></h1>
<p><%= @picture.description %></p>
Updated at <%= @picture.updated_at.strftime('%Y-%m-%d')%><br><br>
<%= image_tag @picture.photo%>

<h2> Comments</h2><br>
<% @comments.each do |comment| %>
<%= comment.content %><br>
<%= time_ago_in_words(comment.created_at) %><br>
<%= link_to "destroy", comment_path(comment), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
    }%><br><br>
<% end %>
<div>
  <%= link_to "Back", :back %>
</div>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>